
modLoader="javafml"

loaderVersion="[36,)"

license="All rights reserved"

[[mods]] #mandatory

modId="icefeeling" #mandatory

version="${file.jarVersion}" #mandatory
displayName="IceFeeling" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Halloweed mod for IceFeeling Faction PVP Server
'''

[[dependencies.icefeeling]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.icefeeling]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5, 1.17]"
ordering="NONE"
side="BOTH"
